### ISSUE TITLE
Ubuntu 16.04 installl

### ISSUE THREAD

**Issue by ivandc33** [unclehook/WatchOCR#1]
Hi thank you for a great script...does exactly what I was looking for.  Can you explain what the optional packages are for?
I manged to get this working on a fresh install of Ubuntu 16.04 server.  Just not sure what the optional packages are for or what version of Linux this should be ran on for best performance.  

Thank you.

**Comment by unclehook** [comment]
Hi ivandc33,
thank you for the compliments but the true work was made by [rlangner](https://sourceforge.net/u/rlangner/profile/), i only extracted the main scripts it from the deb, made some little correction and then put here to be more simple to use in recent linux versions.

The optional packages (oracle-java6-installer, ant, ZXing-1.6) are needed for qrcode file rename.

The main idea of rlangner, i suppose, was
1. use a zebra printer (or similar) to generatea a qrcode with the name of the future file
2. paste the qrcode label on the original document before the scan
3. leave to watchocr the job to scan then rename the file

Sincerly, i never used this function.

I think, you can try using using current [supported java versions in Ubuntu](https://www.atlantic.net/community/howto/install-java-jre-jdk-on-ubuntu-16-04/) and the last version of [zxing](https://github.com/zxing/zxing/).

I hope I was helpful
